extends:
  - stylelint-config-recommended-scss
rules:
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - value
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
  property-no-unknown:
    - true
    - ignoreProperties:
        - composes
  rule-empty-line-before:
    - always
    - except:
        - after-single-line-comment
        - first-nested
  max-empty-lines:
    - 1
    - ignore:
        - comments
