extends:
    - stylelint-config-recommended-scss
rules:
    selector-pseudo-class-no-unknown:
        - true
        - ignorePseudoClasses:
            - global
    property-no-unknown:
        - true
        - ignoreProperties:
            - composes
