version: '2'
services:
    wordpress:
        restart: on-failure:10
        environment:
            DB_USER: $DB_USER
            DB_PASS: $DB_PASS
            PLUGINS: >-
                academic-bloggers-toolkit,
                google-analytics-dashboard-for-wp,
                rest-api,
                sendgrid-email-delivery-simplified,
                tablepress,
                tinymce-advanced,
                ultimate-member,
                wpdiscuz,
                [Basic-Auth-master]https://github.com/WP-API/Basic-Auth/archive/master.zip,
                [um-recaptcha]http://bit.ly/um-recaptcha,
    db:
        restart: on-failure:10
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASS
