version: '3'
services:
    wordpress:
        environment:
            URL_REPLACE: http://localhost:8080
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG: 'true'
            WP_VERSION: nightly
            EXTRA_PHP: |
                define( 'ALIEM_API_KEY', '${ALIEM_API_KEY?ALIEM_API_KEY not defined in .env}' );
                define( 'RECAPTCHA_KEY', '${RECAPTCHA_KEY?RECAPTCHA_KEY not defined in .env}' );
            PLUGINS: >-
                academic-bloggers-toolkit
                [Basic-Auth]https://github.com/WP-API/Basic-Auth/archive/master.zip
                jetpack
                mce-table-buttons
                query-monitor
                sendgrid-email-delivery-simplified
                ultimate-member
                w3-total-cache
                wp-smushit
        ports:
            - 8080:80
        volumes:
            - ./dist:/app/wp-content/themes/aliemu
