version: '2'
services:
    wordpress:
        extends:
            file: lib/compose.yml
            service: wordpress_prod
        links:
            - db
    db:
        extends:
            file: lib/compose.yml
            service: db_prod
volumes:
    data: {}
