version: '3'
services:
    wordpress:
        environment:
            URL_REPLACE: http://localhost:8080
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG: 'true'
            WP_VERSION: nightly
        ports:
            - 8080:80
        volumes:
            - ./dist:/app/wp-content/themes/aliemu
