<?php

/**
 * Adds "Course Short Description" field to the block meta.
 * @param  [type] $post_args [description] // FIXME: Chris what type is this?
 * @return [type]            [description]
 */
function learndash_course_grid_post_args($post_args) {
    foreach($post_args as $key => $post_arg) {
		if($post_arg["post_type"] == "sfwd-courses") {
			$course_short_description = array(
                'name' => __('Course Short Description', 'learndash_course_grid'),
                'type' => 'textarea',
                'help_text' => __('A short description of the course to show on course list generated by course list shortcode.', 'learndash_course_grid'),
            );
			$post_args[$key]["fields"] = array("course_short_description" => $course_short_description) + $post_args[$key]["fields"];
		}
	}
	return $post_args;
}
add_filter("learndash_post_args", "learndash_course_grid_post_args", 10, 1);
