#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR=$(cd $SCRIPTDIR && cd ../ && pwd || exit)
machine_name=aliemu

# Pretty colors
ORANGE='\033[0;33m'
BOLD='\E[1m'
NC='\033[0m'

type rsync &>/dev/null
if [[ $? == 1 ]]; then
    echo '=> Error: rsync must be installed.'
    exit 1
fi

# Compile the code
$ROOTDIR/node_modules/.bin/gulp build

eval "$(ssh-agent -s)" &>/dev/null
ssh-add "$HOME/.ssh/DO_${machine_name}_rsa" &>/dev/null

if [ -z "$(ssh-keygen -F "$(docker-machine ip $machine_name)")" ]; then
  ssh-keyscan -H "$(docker-machine ip $machine_name)" >> ~/.ssh/known_hosts
fi

echo -e "${ORANGE}${BOLD}==> Deploying...${NC}"
rsync --info=progress2 -aOz --chown=www-data:www-data --no-p -e "ssh -i ~/.ssh/DO_${machine_name}_rsa" "$ROOTDIR/dist" "$(docker-machine ip $machine_name)":/app
echo -e "${ORANGE}${BOLD}==> Deploy Finished.${NC}"
