#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR=$(cd $SCRIPTDIR && cd ../ && pwd || exit)

# Pretty colors
ORANGE='\033[0;33m'
BOLD='\E[1m'
NC='\033[0m'

# Compile the code
$ROOTDIR/node_modules/.bin/gulp build

type rsync &>/dev/null
if [[ $? == 1 ]]; then
    echo '=> Error: rsync must be installed.'
    exit 1
fi

# Exit if the DSA file doesn't exist
if [[ ! -f ./data/aliemu_dsa ]]; then
    echo '=> Error: You must have the file "aliemu_dsa" located within your data directory'
    exit 1
fi

chmod 400 $ROOTDIR/data/aliemu_dsa
eval "$(ssh-agent -s)" &>/dev/null
ssh-add $ROOTDIR/data/aliemu_dsa &>/dev/null

echo -e "${ORANGE}${BOLD}==> Deploying...${NC}"
rsync --progress -az -e "ssh -i $ROOTDIR/data/aliemu_dsa -p 18765" "$ROOTDIR/dist/Divi-child/" aliemu@c7563.sgvps.net:public_html/wp-content/themes/Divi-child
echo -e "${ORANGE}${BOLD}==> Deploy Finished.${NC}"
