// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1e5bb9f454be744f9447860b6109c14246f09107/react-datepicker/react-datepicker.d.ts
declare module 'react-datepicker' {
    interface ReactDatePicker {
        className?: string;
        dateFormat?: string;
        dateFormatCalendar?: string;
        disabled?: boolean;
        endDate?: {};
        excludeDates?: any[];
        filterDate?(): any;
        id?: string;
        includeDates?: any[];
        isClearable?: boolean;
        locale?: string;
        maxDate?: {};
        minDate?: {};
        name?: string;
        onBlur?(): any;
        onChange(): any;
        onChange(date?: any): any;
        onFocus?(): any;
        placeholderText?: string;
        popoverAttachment?: string;
        popoverTargetAttachment?: string;
        popoverTargetOffset?: string;
        readOnly?: boolean;
        renderCalendarTo?: any;
        required?: boolean;
        selected?: {};
        showYearDropdown?: boolean;
        startDate?: {};
        tabIndex?: number;
        tetherConstraints?: any[];
        title?: string;
        todayButton?: string;
    }
    let ReactDatePicker: React.ClassicComponentClass<ReactDatePicker>;
    export = ReactDatePicker;
}
