#!/usr/bin/env bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR=$(cd "$SCRIPTDIR" && cd ../../ && pwd || exit)
sync_all=false

while getopts "a" o; do
    case "${o}" in
        a)
            sync_all=true
            ;;
    esac
done

# Change these based on the installation
server_user='aliemu'
theme_name='aliemu'

# shellcheck disable=SC1091,SC1090
source "$SCRIPTDIR"/helpers || exit 1

if [[ $(docker-machine ls -q --filter "name=$server_user" | wc -l) == 0 ]]; then
    ERROR "A Docker machine named $server_user could not be found"
fi

docker-machine scp -r -d "$ROOTDIR/dist/$theme_name" "$server_user:/home/$server_user/app/wp-content/themes"

if [ "$sync_all" = true ]; then
    docker-machine scp -r -d "$ROOTDIR/wp-content/themes/Divi" "$server_user:/home/$server_user/app/wp-content/themes"
    docker-machine scp -r -d "$ROOTDIR/wp-content/plugins/sfwd-lms" "$server_user:/home/$server_user/app/wp-content/plugins"
    docker-machine scp -r -d "$ROOTDIR/wp-content/plugins/learndash-propanel" "$server_user:/home/$server_user/app/wp-content/plugins"
fi
