#!/usr/bin/env bash

SCRIPTDIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )"
ROOTDIR=$( cd "$SCRIPTDIR" && cd ../../ && pwd || exit )
sync_all=false
initial_deploy=false

while getopts "ai" o; do
    case "${o}" in
        a)
            sync_all=true
            ;;
        i)
            initial_deploy=true
            sync_all=true
            ;;
    esac
done

declare base_theme_name
declare machine_name
declare machine_user
declare theme_name
declare -a local_plugins

# shellcheck disable=1090
{
    . "$SCRIPTDIR/helpers" || exit 1
    . "$SCRIPTDIR/variables" || exit 1
}

if [[ $(docker-machine ls -q --filter "name=$machine_name" | wc -l) == 0 ]]; then
    ERROR "A Docker machine named $machine_name could not be found"
fi

docker-machine ssh "$machine_name" "
    rm -rf /home/$machine_user/app/wp-content/themes/$theme_name/*
"

h2 "Deploying $theme_name"
docker-machine scp -r -d "$ROOTDIR/dist/$theme_name" "$machine_name:/home/$machine_user/app/wp-content/themes"

if [ "$initial_deploy" = true ]; then
    # Make sure files exist
    # [ ! -f "$ROOTDIR/.env" ] && ERROR '.env file cannot be located.'
    [ ! -f "$ROOTDIR/lib/production.yml" ] && ERROR 'production.yml file cannot be located.'
    [ ! -f "$ROOTDIR/data/database.sql" ] && ERROR 'database.sql file cannot be located.'

    # docker-compose file
    docker-machine scp -r -d "$ROOTDIR/lib/production.yml" "$machine_name:/home/$machine_user/app/docker-compose.yml"

    # database export
    docker-machine scp -r -d "$ROOTDIR/data/database.sql" "$machine_name:/home/$machine_user/app/data/database.sql"

    # env file
    # docker-machine scp -r -d "$ROOTDIR/.env" "$machine_name:/home/$machine_user/app/.env"

    # uploads
    docker-machine scp -r -d "$ROOTDIR/wp-content/uploads" "$machine_name:/home/$machine_user/app/wp-content"
fi

if [ "$sync_all" = true ]; then
    h2 "Removing old version of $base_theme_name"
    docker-machine ssh "$machine_name" "
        rm -rf /home/$machine_user/app/wp-content/themes/$base_theme_name/*
    "

    h2 "Deploying $base_theme_name"
    docker-machine scp -r -d "$ROOTDIR/wp-content/themes/$base_theme_name" "$machine_name:/home/$machine_user/app/wp-content/themes"

    h2 "Deploying plugins"
    for plugin in "${local_plugins[@]}"; do
        h3 "Removing old version of $plugin"
        docker-machine ssh "$machine_name" "
            rm -rf /home/$machine_user/app/wp-content/plugins/$plugin/*
        "
        h3 "Deploying $plugin"
        docker-machine scp -r -d "$ROOTDIR/wp-content/plugins/$plugin" "$machine_name:/home/$machine_user/app/wp-content/plugins"
    done
fi

h2 "Adjusting filesystem permissions on remote host"
docker-machine ssh "$machine_name" "
    sudo chown -R www-data:$machine_user /home/$machine_user/app
"
