#!/usr/bin/env bash

TERM=${TERM:-xterm}
RED='\033[0;31m'
ORANGE='\033[0;33m'
CYAN='\033[0;36m'
BOLD='\E[1m'
NC='\033[0m'

h2() {
    echo -e "${ORANGE}${BOLD}==>${NC}${BOLD} $*${NC}"
}

h3() {
    printf "%b " "${CYAN}${BOLD}  ->${NC} $*"
}

ERROR() {
  echo -e "${RED}=> ERROR: $1.${NC}"
  exit 1
}
