#!/bin/bash

if [[ $(uname -n) != 'aliemu' ]]; then
    echo "This script is meant to be run on the server only."
    exit 0
fi

case $1 in
    theme)
        find wp-content/themes -name '*.js' -print0 | xargs -r0 -I % uglifyjs -c dead_code,unused,drop_debugger,drop_console -o % %
        find wp-content/themes -name '*.css' -print0 | xargs -r0 -I % csso % %
        ;;
    plugins)
        find wp-content/plugins -name '*.js' -print0 | xargs -r0 -I % uglifyjs -c dead_code,unused,drop_debugger,drop_console -o % %
        find wp-content/plugins -name '*.css' -print0 | xargs -r0 -I % csso % %
        ;;
    *)
        echo "Command not recognized. Available commands: 'theme', 'plugins'"
        exit 0
        ;;
esac
