#!/usr/bin/env bash

# Globals
SCRIPTDIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )"
ROOTDIR="$( cd "$SCRIPTDIR" && cd ../../ && pwd || exit )"

# Change these based on the installation
declare machine_name
declare machine_user
declare base_theme_name
declare -a local_plugins

# shellcheck disable=1090
{
    . "$SCRIPTDIR/helpers" || exit 1
    . "$SCRIPTDIR/variables" || exit 1
}

 # Does the machine exist?
if [[ $(docker-machine ls -q --filter "name=$machine_name" | wc -l) == 0 ]]; then
    ERROR "A Docker machine named $machine_name could not be found"
fi

# Check ownership of wp-content
if [[ $( find "$ROOTDIR/wp-content" ! -user "$USER" -print -quit | wc -l ) -ne 0 ]]; then
    h2 'Need sudo priveledges to take ownership of wp-content directory'
    sudo chown -R "$USER" "$ROOTDIR"/wp-content
fi

main() {

    if [[ $# == 0 ]]; then
        get_uploads
        get_database
        exit 0
    fi

    case "$1" in
        init)
            get_theme
            get_plugins
            get_uploads
            get_database;;
        get)
            case "$2" in
                uploads)
                    get_uploads;;
                plugins)
                    get_plugins;;
                theme)
                    get_theme;;
                database)
                    get_database;;
                *)
                    h2 "'get' subcommmand must be either 'uploads', 'plugins', 'theme', or 'database'" && exit 0
            esac;;
        *)
            h2 "The only available commands are 'init' and 'get'" && exit 0
    esac
}

get_uploads() {
    h2 "Downloading uploads from server..."
    docker-machine scp -r -d "$machine_name:/home/$machine_user/app/wp-content/uploads/" "$ROOTDIR/wp-content/uploads"
}

get_plugins() {
    local plugin
    h2 "Retrieving plugins"
    for plugin in "${local_plugins[@]}"; do
        h3 "Retrieving plugin: $plugin"
        docker-machine scp -r -d "$machine_name:/home/$machine_user/app/wp-content/plugins/$plugin" "$ROOTDIR/wp-content/plugins"
    done
}

get_theme() {
    h2 "Retrieving Theme"
    docker-machine scp -r -d "$machine_name:/home/$machine_user/app/wp-content/themes/$base_theme_name" "$ROOTDIR/wp-content/themes"
}

get_database() {
    rm -f "$ROOTDIR/data/database.sql.bak"
    mv "$ROOTDIR/data/database.sql" "$ROOTDIR/data/database.sql.bak" 2>/dev/null

    h2 "Exporting database..."
    docker-machine ssh "$machine_name" "
    cd /home/$machine_user/app
    sudo -u $machine_user docker-compose exec -T wordpress /bin/bash -c 'wp db export /data/database.sql --allow-root'
    "

    h2 "Downloading database to local machine..."
    docker-machine scp -r -d "$machine_name:/home/$machine_user/app/data/database.sql" "$ROOTDIR/data/database.sql"

    h2 "Export complete!"
}

main "$@"
